### ISSUE TITLE
Todo for scripts/benchmark/cuda.py

### ISSUE THREAD

**Issue by lichen-liu** [qsnsidney/tuss#12]
1. Add
```
if __name__ == '__main':
```
to the script body, so that the script becomes a python module.
To run, `python3 -m scripts.benchmark.cuda_benchmark`

2. Rename cuda_benchmark.py to cuda.py
3. Move benchmark/*.ic.bin into benchmark/ic/
4. Add some output messages in cuda_benchmark.py so that it is easy to see whether it is running
5. Store benchmark results into benchmark/perf/cuda
6. Correctly handle benchmark tmp files
7. Store some meta data around the benchmark results
    - date time:
        - as result name (folder or csv filename)
    - version label: can be added via the cuda_benchmark.py script
        - store that in csv as comment with # at the top, or as individual metadata file

**Comment by haiqi96** [comment]
#1234 are done in 5f4c32dece2fa1da642ccdc8cb4517071ac14c80

for 5, 6, 7. I have a few concern:

1.Some one may want to run benchmark with local changes. in this case we don't want to over create too many folders because it might cause confusion
2. some one may run benchmark with uncommited changes, in this case can the metadata catches those changes? It might only make sense to store the data if something is committed and change the main.cu. However, it will also make it hard to analyze the data if we store data for every commit. Ideally we should only store the data that is "important enough"

The whole point of metadata is to make the data meaningful, so if we want to go with this way it must have enough information to make the data meaningful to us

**Comment by lichen-liu** [comment]
addressed
